apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openproject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openproject
    spec:
      containers:
        - name: openproject
          image: openproject/community:latest
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 8080
            name: openproject
          volumeMounts:
          - mountPath: /var/openproject
            name: openproject
                  
      volumes:
        - name: openproject
          persistentVolumeClaim:
            claimName: openproject-claim
